genre_map = {
	"industrial":"industrial",
	"gothic":"industrial",
	"krautrock":"industrial",
	"avant-garde":"industrial",
	"avant":"industrial",
	"garde":"industrial",
	"deathrock":"industrial",
	"noise":"industrial",
	"dark ambient":"industrial",
	"darkwave":"industrial",
	"dark wave":"industrial",
	"dark-wave":"industrial",
	"coldwave":"industrial",
	"cold wave":"industrial",
	"cold-wave":"industrial",
	"electro-industrial":"industrial",
	"aggreppo":"industrial",
	"metal":"metal",
	"progressive":"metal",
	"nwobhm":"metal",
	"thrash":"metal",
	"doom":"metal",
	"grindcore":"metal",
	"grind core":"metal",
	"grind-core":"metal",
	"rock":"rock",
	"rocknroll":"rock",
	"rock'n":"rock",
	"surf":"rock",
	"garage":"rock",
	"pyschedelic":"rock",
	"krautrock":"rock",
	"glamrock":"rock",
	"glam":"rock",
	"heartland":"rock",
	"a.o.r":"rock",
	" aor ":"rock",
	"punk":"rock",
	"skacore":"rock",
	"ska-core":"rock",
	"ska core":"rock",
	"nowave":"rock",
	"no wave":"rock",
	"no-wave":"rock",
	"newwave":"rock",
	"new-wave":"rock",
	"new wave":"rock",
	"psychobilly":"rock",
	"pyscho billy":"rock",
	"pyscho-billy":"rock",
	"new romantics":"rock",
	"synth":["rock", "pop"],
	"skate punk":"rock",
	"skatepunk":"rock",
	"math":"rock",
	"crunkcore":"rock",
	"hardcore":"rock",
	"dream pop":"rock",
	"dreampop":"rock",
	"dream-pop":"rock",
	"shoegaze":"rock",
	"shoe gaze":"rock",
	"shoe-gaze":"rock",
	"grunge":"rock",
	"rapcore":"rock",
	"britpop":"rock",
	" emo ":"rock",
	"indie":"rock",
	"freakfolk":"rock",
	"freak folk":"rock",
	"freak-folk":"rock",
	"folk":["rock", "pop"],
	"pop":"pop",
	" schlager ":"pop",
	"skiffle":"pop",
	"crooner":"pop",
	"bubblegum":"pop",
	"bubble gum":"pop",
	"bubble-gum":"pop",
	"teeny bop":"pop",
	"teenybop":"pop",
	"teeny-bop":"pop",
	"singer/songwriter":"pop",
	"singer / songwriter":"pop",
	"singer songwriter":"pop",
	"singer-songwriter":["rock","pop"],
	"powerpop":"pop",
	"power-pop":"pop",
	"brill building":"pop",
	" twee ":"pop",
	"hi-nrg":"pop",
	"disco":["pop","r&b"],
	"country":"country",
	"honky":"country",
	"blue grass":"country",
	"bluegrass":"country",
	"blue-grass":"country",
	"outlaw":"country",
	"americana":"country",
	"r&b":"r&b",
	"rhythm 'n' blues":"r&b",
	"rhythm 'n blues":"r&b",
	"rhythm n' blues":"r&b",
	"doo wop":"r&b",
	"doo-wop":"r&b",
	"doowop":"r&b",
	"soul":"r&b",
	" go go ":"r&b",
	"go-go":"r&b",
	"funk":"r&b",
	" swing ":["r&b","jazz"],
	"gospel":"gospel",
	"ragtime":"gospel",
	" stride ":"gospel",
	"christian":"gospel",
	"blues":"blues",
	"vaudeville":"blues",
	"boogie woogie":"blues",
	"dixieland":"jazz",
	"dixie land":"jazz",
	"jazz":"jazz",
	"bebop":"jazz",
	"be-bop":"jazz",
	"be bop":"jazz",
	"hard bop":"jazz",
	"hardbop":"jazz",
	"hard-bop":"jazz",
	"reggae":"reggae",
	"ska":"reggae",
	" mento ":"reggae",
	"rocksteady":"reggae",
	"dancehall":"reggae",
	"ragga":"reggae",
	"hip hop":"hip hop",
	"hip-hop":"hip hop",
	"hiphop":"hip hop",
	" rap ":"hip hop",
	" rapper ":"hip hop",
	"miami bass":"hip hop",
	" trap ":"hip hop",
	"glitch hop":["hip hop","EDM"],
	"glitch-hop":["hip hop","EDM"],
	"crunk":"hip hop",
	"dirty south":"hip hop",
	"edm":"EDM",
	"electronic dance":"EDM",
	"electro":["hip hop","EDM"],
	"breakdance":"EDM",
	"breakbeat":"EDM",
	"ambient":["hip hop","EDM"],
	"future bass":"EDM",
	"future garage":"EDM",
	"broken beat":"EDM",
	"trapstep":"EDM",
	"drum 'n' bass":"EDM",
	"jungle":"EDM",
	"idm":"EDM",
	"dubstep":"EDM",
	"darkstep":"EDM",
	"techstep":"EDM",
	"hardstep":"EDM",
	"breakcore":"EDM",
	"techno":"EDM",
	"speedcore":"EDM",
	"terrorcore":"EDM",
	"trance":"EDM",
	"trancecore":"EDM",
	"house music":"EDM",
	"electro house":"EDM",
	"downtempo":"EDM",
	"electronica":"EDM",
	"chill-out":"EDM",
	"chillout":"EDM",
	"trip hop":"EDM",
	"muzak":"EDM",
	"vaporwave":"EDM",
	"classical":"classical",
	"opera":"classical",
	"choral":"classical",
	"baroque":"classical"
}