instruments = {
	"brass" : "horns",
	"woodwind" : "horns",
	"wood wind" : "horns",
	"trumpet" : "horns",
	 "cornet" : "horns",
	 "trombon" : "horns",
	 "euphonium" : "horns",
	 "tuba" : "horns",
	 "tubist" : "horns",
	 "sousaphon" : "horns",
	 "horn" : "horns",
	 "flute" : "horns",
	 "flautist" : "horns",
	 "clarinet" : "horns",
	 "saxophon" : "horns",
	 "piccolo" : "horns",
	 "bassoon" : "horns",
	 "oboe" : "horns",
	 "oboist" : "horns",
	 "violin" : "strings",
	 "cello" : "strings",
	 "dulcimer" : "strings",
	 "harp" : "strings",
	 "percussion" : "percussion",
	 "xylophone" : "percussion",
	 "vibraphone" : "percussion",
	 "marimba" : "percussion",
	 "bongo" : "percussion",
	 "piano" : "keys",
	 "keys" : "keys",
	 "keyboard" : "keys",
	 "accordion" : "keys",
	 "organ" : "keys",
	 "synthesizer" : "keys",
	 "keytar" : "keys",
	 "mellotron" : "keys",
	 "harpsichord" : "keys",
	 "vocalist" : "vocalist",
	 "singer" : "vocalist",
	 "rapper" : "vocalist",
	 "a cappella" : "vocalist",
	 "acappella" : "vocalist",
	 "dj" : "dj",
	 "d.j." : "dj",
	 "disc jockey" : "dj",
	 "guitar" : "guitar",
	 "bassist" : "bass",
	 "bass player" : "bass",
	 "drummer" : "drums"
}